### PR TITLE
Add a plugin for ImageIO, which handles TIFF files.

### LINKED ISSUE #6: Error: class pl.psnc.dl.ege.exception.ConverterException Couldn't find images directory.
I have a Docx document which fails Docx to xHTML conversion with the following error:

```
Error: class pl.psnc.dl.ege.exception.ConverterException

Couldn't find images directory.
```

The minimal reproducible test case (a single TIFF image) can be found here: http://cl.ly/0W1u360d0i2f

### PR DESCRIPTION
**Pull request by jure**
This fixes #6.

Let me know what you think.

### CODE REVIEW

**Comment by sebastianrahtz** [comment]
looks perfect

**Comment by jure** [comment]
@sebastianrahtz: For some reason, I'm still getting this error in the latest build. Any idea why that might be? Did something go wrong with the build process, given that it's a new dependency?

**Comment by jure** [comment]
In the latest build the `tei-converter.jar` (the affected jar) is 39831 bytes:

```
-rw-r--r-- 1 root root   39831 Jun 30 09:58 tei-converter-0.5.jar
```

Locally, when I build from the `tiff_fix` branch and the TIFF images convert OK, the `tei-converter.jar` is 39853 bytes:

```
-rw-rw-r-- 1 vagrant vagrant 39853 Jul 21 12:06 tei-converter-0.5.jar
```

Any idea why these two files would be different following the same build process? I'm confused.

**Comment by sebastianrahtz** [comment]
Sorry I am in a limbo at the momnent, Recovering from cancer but waiting for news on potential new problems with brain tumours, will let you know later this week!

**Comment by jure** [comment]
I’m very sorry to hear that, Sebastian! I’m lost for words, but I wish you all the best and a quick recovery.

I can’t do much, but let me know if I can do anything to help out with OxGarage in your absence. I would love to help!

**Pull request merged**
