### PR TITLE
pass the temp directory of the unpacked source odt to xslt

### PR DESCRIPTION
**Pull request by mpetris**

### CODE REVIEW

**Comment by sebastianrahtz** [comment]
I changed this from dot-dir to just "dir", as that was already being used in the XSL

**Comment by mpetris** [comment]
I tried that before but somehow it doesn't work:
'dir' then always has the value '.' but it should be something like
/var/cache/oxgarage/temp/416a6c80-9949-4ac3-8d01-4129fe711121/.
And since docx processing uses a different name as well I thought it has
to be like that.
Does 'dir' get overridden with '.' somewhere later or am I doing
something wrong?
Thanks,
Marco

Am 12.01.2015 um 10:22 schrieb Sebastian Rahtz:

**Comment by sebastianrahtz** [comment]
i changed oxgarge to pass on the value for dir, as per your change to
dot-dir. that should work?

On 12 January 2015 at 10:35, mpetris <notifications@github.com> wrote:

> I tried that before but somehow it doesn't work:
> 'dir' then always has the value '.' but it should be something like
> /var/cache/oxgarage/temp/416a6c80-9949-4ac3-8d01-4129fe711121/.
> And since docx processing uses a different name as well I thought it has
> to be like that.
> Does 'dir' get overridden with '.' somewhere later or am I doing
> something wrong?
> Thanks,
> Marco
>
> Am 12.01.2015 um 10:22 schrieb Sebastian Rahtz:
> >
> > I changed this from dot-dir to just "dir", as that was already being
> > used in the XSL
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sebastianrahtz/oxgarage/pull/2#issuecomment-69544507>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebastianrahtz/oxgarage/pull/2#issuecomment-69552063>.
>



-- 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by mpetris** [comment]
With getting odt-dir passed in I did an assignment from odt-dir to dir.
That worked. After my assignment dir had the right value and it stayed
that way.
With getting dir passed in I cannot make the assignment because
obviously it would give me a 'Duplicate global variable declaration'
error. So I removed the assignment code from my custom xsl and dir
should have the right value anyway as it is set from the Java code
directly now. But somehow it doesn't. I don't know if 'dir' has some
special treatment or it gets overridden somewhere. It always show me the
default value which is '.'


Am 12.01.2015 um 11:42 schrieb Sebastian Rahtz:
> i changed oxgarge to pass on the value for dir, as per your change to
> dot-dir. that should work?
>

**Comment by sebastianrahtz** [comment]
maddening. I will have to test this myself and see if I can understand what
is happening. sorry, it may take me a few days.

On 12 January 2015 at 11:14, mpetris <notifications@github.com> wrote:

> With getting odt-dir passed in I did an assignment from odt-dir to dir.
> That worked. After my assignment dir had the right value and it stayed
> that way.
> With getting dir passed in I cannot make the assignment because
> obviously it would give me a 'Duplicate global variable declaration'
> error. So I removed the assignment code from my custom xsl and dir
> should have the right value anyway as it is set from the Java code
> directly now. But somehow it doesn't. I don't know if 'dir' has some
> special treatment or it gets overridden somewhere. It always show me the
> default value which is '.'
>
>
> Am 12.01.2015 um 11:42 schrieb Sebastian Rahtz:
> > i changed oxgarge to pass on the value for dir, as per your change to
> > dot-dir. that should work?
> >
> > On 12 January 2015 at 10:35, mpetris <notifications@github.com> wrote:
> >
> > > I tried that before but somehow it doesn't work:
> > > 'dir' then always has the value '.' but it should be something like
> > > /var/cache/oxgarage/temp/416a6c80-9949-4ac3-8d01-4129fe711121/.
> > > And since docx processing uses a different name as well I thought it
> > has
> > > to be like that.
> > > Does 'dir' get overridden with '.' somewhere later or am I doing
> > > something wrong?
> > > Thanks,
> > > Marco
> > >
> > > Am 12.01.2015 um 10:22 schrieb Sebastian Rahtz:
> > > >
> > > > I changed this from dot-dir to just "dir", as that was already being
> > > > used in the XSL
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > >
> > <https://github.com/sebastianrahtz/oxgarage/pull/2#issuecomment-69544507>.
>
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <https://github.com/sebastianrahtz/oxgarage/pull/2#issuecomment-69552063>.
>
> > >
> >
> >
> >
> > --
> >
> > Sebastian Rahtz
> >
> > Director (Research) of Academic IT
> >
> > University of Oxford IT Services
> >
> > 13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431
> >
> >
> > Não sou nada.
> >
> > Nunca serei nada.
> >
> > Não posso querer ser nada.
> >
> > À parte isso, tenho em mim todos os sonhos do mundo.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sebastianrahtz/oxgarage/pull/2#issuecomment-69552883>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebastianrahtz/oxgarage/pull/2#issuecomment-69556064>.
>



-- 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by mpetris** [comment]
I found the problem, sorry, it was caused by a wrong maven build on my
side, so the 'dir' parameter works as well.
There were plans to use the software next month, is there a release
scheduled this month or next month so that we could use our changes with
the webservice at tei-c.org?

Am 13.01.2015 um 17:46 schrieb Sebastian Rahtz:
> maddening. I will have to test this myself and see if I can understand
> what
> is happening. sorry, it may take me a few days.
>

**Comment by sebastianrahtz** [comment]
I can make a release this week no problem

**Comment by mpetris** [comment]
Excellent! Thanks!

Am 14.01.2015 um 09:59 schrieb Sebastian Rahtz:
> I can make a release this week no problem
>
> Sent from my iPhone
>

**Comment by sebastianrahtz** [comment]
i have now made a new release

sebastian

**Pull request merged**
